/**
 * BOM (Bill of Materials) and Pick-and-Place export for PCB Studio.
 * Professional manufacturing outputs for PCB assembly.
 */

import { getFootprint } from './footprintLib.js';

/**
 * Generate BOM as CSV string.
 * Groups components by value + footprint and counts quantities.
 * @param {object} doc
 * @returns {string} CSV content
 */
export function generateBomCsv(doc) {
  const placements = doc.placements || [];
  if (placements.length === 0) return 'No components placed.';

  // Group by value + footprint
  const groups = new Map();
  for (const pl of placements) {
    const fp = getFootprint(pl.footprintId);
    const key = `${pl.value || '—'}|${pl.footprintId}`;
    if (!groups.has(key)) {
      groups.set(key, {
        value: pl.value || '—',
        footprint: pl.footprintId,
        footprintName: fp?.name || pl.footprintId,
        family: fp?.family || '?',
        refs: [],
      });
    }
    groups.get(key).refs.push(pl.ref || '?');
  }

  // Sort by reference designator
  const sorted = [...groups.values()].sort((a, b) => {
    const ra = a.refs[0] || '';
    const rb = b.refs[0] || '';
    return ra.localeCompare(rb, undefined, { numeric: true });
  });

  const lines = ['"Item","Qty","Reference","Value","Footprint","Description"'];
  let item = 1;
  for (const g of sorted) {
    const refs = g.refs.sort((a, b) => a.localeCompare(b, undefined, { numeric: true })).join(', ');
    lines.push(`${item},${g.refs.length},"${refs}","${g.value}","${g.footprint}","${g.footprintName}"`);
    item++;
  }

  return lines.join('\n');
}

/**
 * Generate Pick-and-Place (centroid) file as CSV.
 * Format compatible with assembly houses (JLCPCB, PCBWay, etc.).
 * @param {object} doc
 * @returns {string} CSV content
 */
export function generatePickAndPlaceCsv(doc) {
  const placements = doc.placements || [];
  if (placements.length === 0) return 'No components placed.';

  const lines = ['"Designator","Val","Package","Mid X","Mid Y","Rotation","Layer"'];

  const sorted = [...placements].sort((a, b) =>
    (a.ref || '').localeCompare(b.ref || '', undefined, { numeric: true })
  );

  for (const pl of sorted) {
    const x = (Number(pl.x) || 0).toFixed(4);
    const y = (Number(pl.y) || 0).toFixed(4);
    const rot = (Number(pl.rot) || 0).toFixed(1);
    const layer = pl.layer === 'B.Cu' ? 'Bottom' : 'Top';
    lines.push(`"${pl.ref || '?'}","${pl.value || ''}","${pl.footprintId}",${x},${y},${rot},"${layer}"`);
  }

  return lines.join('\n');
}

/**
 * Generate IPC-D-356 netlist (bare board test) file.
 * Used for electrical testing after fabrication.
 * @param {object} doc
 * @returns {string}
 */
export function generateIpcD356(doc) {
  const lines = [];
  lines.push('C  IPC-D-356 Netlist generated by PCB Studio');
  lines.push(`C  Board: ${doc.meta?.name || 'Untitled'}`);
  lines.push(`C  Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push('P  UNITS CUST 0');

  for (const pl of (doc.placements || [])) {
    const fp = getFootprint(pl.footprintId);
    if (!fp?.pads) continue;
    const nets = pl.padNets || {};
    for (const pad of fp.pads) {
      const net = nets[pad.num] || nets[pad.id] || 'N/C';
      const rot = (Number(pl.rot) || 0) * Math.PI / 180;
      const cx = pl.x + pad.x * Math.cos(rot) - pad.y * Math.sin(rot);
      const cy = pl.y + pad.x * Math.sin(rot) + pad.y * Math.cos(rot);
      const xStr = Math.round(cx * 10000).toString().padStart(6, ' ');
      const yStr = Math.round(cy * 10000).toString().padStart(6, ' ');
      const netPad = net.padEnd(14);
      const ref = (pl.ref || '??').padEnd(6);
      const pn = (pad.num || '?').padStart(4, ' ');
      lines.push(`327${netPad}${ref}${pn}        X${xStr}Y${yStr}X0000Y0000R000 S0`);
    }
  }

  lines.push('999');
  return lines.join('\n');
}

/**
 * Trigger a file download in the browser.
 */
export function downloadTextFile(content, filename) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
