/**
 * Build RS-274X Gerbers for PCB fabrication: all active copper, Edge.Cuts, F/B silk,
 * F/B soldermask openings, F/B paste (SMD), Excellon PTH drill (vias + THT pads).
 * PCB Studio uses SVG-style coords (origin top-left, Y down, mm). Gerber uses Y up.
 * B.Cu mirrors X (back copper film). F/B soldermask uses the same board (x,y) datum — no extra B X mirror.
 */

import JSZip from 'jszip';
import { getFootprint } from './footprintLib.js';
import { activeCopperLayerIds } from './pcbDoc.js';

const GERBER_HEADER_EDGE = (name) =>
    [
        'G04 ' + (name || 'Edge.Cuts') + '*',
        'G04 Generated by NozePlot PCB Studio*',
        'G04 board profile (legacy RS-274X, no X2 %TF attributes)*',
    ].join('\n') + '\n';

/** Copper layer header — G04 only so old Gerber viewers do not choke on %TF.* X2 syntax. */
function buildCopperGerberHeader(layer) {
    return ['G04 ' + layer + '*', 'G04 Generated by NozePlot PCB Studio*'].join('\n') + '\n';
}

/** Decimal mm for aperture definitions (ADD…C,0.35* etc.). */
function fmtMm(mm) {
    const v = Math.round(Number(mm) * 1e6) / 1e6;
    let s = v.toFixed(6);
    if (s.includes('.')) {
        s = s.replace(/\.?0+$/, '');
    }
    return s;
}

/** Fixed-format coordinate (no `.`) matching `%FSLAX46Y46*%` — 4 integer + 6 fractional digits. */
function fmtCoordGerber(mm) {
    const neg = mm < 0;
    const v = Math.abs(Number(mm));
    const scale = 1e6;
    const rounded = Math.round(v * scale + 1e-9);
    const intPart = Math.floor(rounded / scale);
    const fracPart = rounded % scale;
    const intStr = String(intPart).padStart(4, '0');
    const fracStr = String(fracPart).padStart(6, '0');
    return (neg ? '-' : '') + intStr + fracStr;
}

function xyLine(x, y, op) {
    return `X${fmtCoordGerber(x)}Y${fmtCoordGerber(y)}${op}*\n`;
}

function mirrorX(boardW, x) {
    return boardW - x;
}

function rotLocal(x, y, deg) {
    const r = ((Number(deg) || 0) * Math.PI) / 180;
    const c = Math.cos(r);
    const s = Math.sin(r);
    return [x * c - y * s, x * s + y * c];
}

function padWorld(pl, pad) {
    const [lx, ly] = rotLocal(pad.x, pad.y, pl.rot || 0);
    return [lx + pl.x, ly + pl.y];
}

/** Footprint-local mm → board mm (same as pad origin transform). */
function fpLocalToWorld(pl, lx, ly) {
    const [x, y] = rotLocal(lx, ly, pl.rot || 0);
    return [x + pl.x, y + pl.y];
}

function svgToGerber(doc, svgX, svgY, mirror) {
    const W = Number(doc.meta?.boardWmm) || 80;
    const H = Number(doc.meta?.boardHmm) || 50;
    const gx = mirror ? mirrorX(W, svgX) : svgX;
    const gy = H - svgY;
    return [gx, gy];
}

function padFlashDims(pad, rotDeg) {
    const r = ((Number(rotDeg) || 0) % 360 + 360) % 360;
    const snap = Math.round(r / 90) % 4;
    if (Math.abs(r - snap * 90) < 0.01) {
        if (snap % 2 === 1) return { kind: 'R', w: pad.h, h: pad.w };
        return { kind: 'R', w: pad.w, h: pad.h };
    }
    return { kind: 'C', d: Math.max(pad.w, pad.h) * 0.95 };
}

function padHasPlatedDrill(pad) {
    const d = Number(pad.drill);
    return Number.isFinite(d) && d > 0;
}

/** Extra copper clearance around pads on mask / paste (mm per side). */
const MASK_PAD_MARGIN = 0.06;
const MASK_VIA_MARGIN = 0.05;

function buildCopperGerber(doc, layer) {
    const mirror = layer === 'B.Cu';
    const lines = [];
    lines.push(buildCopperGerberHeader(layer));
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');

    const apMap = new Map();
    let nextAp = 10;

    function ensureRoundDiam(diamMm) {
        const key = `C:${fmtMm(diamMm)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}C,${fmtMm(diamMm)}*%\n`);
        return d;
    }

    function ensureRect(w, h) {
        const key = `R:${fmtMm(w)}X${fmtMm(h)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}R,${fmtMm(w)}X${fmtMm(h)}*%\n`);
        return d;
    }

    // Pads on every copper layer (THT barrels + SMD on outer layers — same flashes all layers for THT).
    for (const pl of doc.placements || []) {
        const fp = getFootprint(pl.footprintId);
        if (!fp) continue;
        for (const pad of fp.pads || []) {
            const [wx, wy] = padWorld(pl, pad);
            const [gx, gy] = svgToGerber(doc, wx, wy, mirror);
            const dims = padFlashDims(pad, pl.rot || 0);
            const ap =
                dims.kind === 'R'
                    ? ensureRect(dims.w, dims.h)
                    : ensureRoundDiam(dims.d);
            lines.push(`D${ap}*\n`);
            lines.push(xyLine(gx, gy, 'D03'));
        }
    }

    for (const v of doc.vias || []) {
        const diam = Number(v.diamMm) || Number(doc.meta?.defaultViaDiamMm) || 0.8;
        const ap = ensureRoundDiam(diam);
        const [gx, gy] = svgToGerber(doc, v.x, v.y, mirror);
        lines.push(`D${ap}*\n`);
        lines.push(xyLine(gx, gy, 'D03'));
    }

    const tracks = (doc.tracks || []).filter((t) => t.layer === layer);
    for (const tr of tracks) {
        const pts = tr.points || [];
        if (pts.length < 2) continue;
        const w = Number(tr.widthMm) || Number(doc.meta?.defaultTrackMm) || 0.35;
        const ap = ensureRoundDiam(w);
        lines.push(`D${ap}*\n`);
        const p0 = pts[0];
        const [g0x, g0y] = svgToGerber(doc, p0[0], p0[1], mirror);
        lines.push(xyLine(g0x, g0y, 'D02'));
        for (let i = 1; i < pts.length; i++) {
            const p = pts[i];
            const [gx, gy] = svgToGerber(doc, p[0], p[1], mirror);
            lines.push(xyLine(gx, gy, 'D01'));
        }
    }

    const polys = (doc.polygons || []).filter((p) => p.layer === layer);
    for (const poly of polys) {
        const pts = poly.points || [];
        if (pts.length < 3) continue;
        lines.push('G36*\n');
        const [gx0, gy0] = svgToGerber(doc, pts[0][0], pts[0][1], mirror);
        lines.push(xyLine(gx0, gy0, 'D02'));
        for (let i = 1; i < pts.length; i++) {
            const [gx, gy] = svgToGerber(doc, pts[i][0], pts[i][1], mirror);
            lines.push(xyLine(gx, gy, 'D01'));
        }
        lines.push(xyLine(gx0, gy0, 'D01'));
        lines.push('G37*\n');
    }

    lines.push('M02*\n');
    return lines.join('');
}

function buildSilkScreenGerber(doc, mirror) {
    const layerName = mirror ? 'B.SilkS' : 'F.SilkS';
    const lines = [];
    lines.push(`G04 ${layerName}*`);
    lines.push('G04 Generated by NozePlot PCB Studio*');
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');
    if (mirror) {
        lines.push('G04 Bottom silk empty — footprint silk is top-side in this editor*\n');
        lines.push('M02*\n');
        return lines.join('');
    }
    const stroke = 0.12;
    lines.push(`%ADD10C,${fmtMm(stroke)}*%\n`);
    lines.push('D10*\n');
    for (const pl of doc.placements || []) {
        const fp = getFootprint(pl.footprintId);
        if (!fp?.silk?.length) continue;
        for (const ln of fp.silk) {
            if (ln?.kind !== 'line') continue;
            const [wx1, wy1] = fpLocalToWorld(pl, ln.x1, ln.y1);
            const [wx2, wy2] = fpLocalToWorld(pl, ln.x2, ln.y2);
            const [g1x, g1y] = svgToGerber(doc, wx1, wy1, false);
            const [g2x, g2y] = svgToGerber(doc, wx2, wy2, false);
            lines.push(xyLine(g1x, g1y, 'D02'));
            lines.push(xyLine(g2x, g2y, 'D01'));
        }
    }
    lines.push('M02*\n');
    return lines.join('');
}

/** Soldermask: positive flashes = openings (no mask over copper / pads). */
function buildSoldermaskGerber(doc, mirror) {
    const layerName = mirror ? 'B.Mask' : 'F.Mask';
    const lines = [];
    lines.push(`G04 ${layerName}*`);
    lines.push('G04 Generated by NozePlot PCB Studio*');
    lines.push('G04 Openings (positive); fab may panelize — verify ring specs*');
    lines.push(
        'G04 Board coords only (no B-side X mirror) — same datum as F_Cu so viewers align mask with pads*',
    );
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');

    const apMap = new Map();
    let nextAp = 10;
    function ensureRoundDiam(diamMm) {
        const key = `C:${fmtMm(diamMm)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}C,${fmtMm(diamMm)}*%\n`);
        return d;
    }
    function ensureRect(w, h) {
        const key = `R:${fmtMm(w)}X${fmtMm(h)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}R,${fmtMm(w)}X${fmtMm(h)}*%\n`);
        return d;
    }

    const m2 = MASK_PAD_MARGIN * 2;

    // F.Mask: all pads + vias. B.Mask: vias + THT only (top SMD has no bottom pad in this model).
    for (const pl of doc.placements || []) {
        const fp = getFootprint(pl.footprintId);
        if (!fp) continue;
        for (const pad of fp.pads || []) {
            if (mirror && !padHasPlatedDrill(pad)) continue;
            const [wx, wy] = padWorld(pl, pad);
            // Do not mirror X for mask: openings are physical (x,y); B.Cu uses mirror for back-copper film only.
            const [gx, gy] = svgToGerber(doc, wx, wy, false);
            const dims = padFlashDims(pad, pl.rot || 0);
            if (dims.kind === 'R') {
                const ap = ensureRect(dims.w + m2, dims.h + m2);
                lines.push(`D${ap}*\n`);
            } else {
                const ap = ensureRoundDiam(dims.d + m2);
                lines.push(`D${ap}*\n`);
            }
            lines.push(xyLine(gx, gy, 'D03'));
        }
    }

    for (const v of doc.vias || []) {
        const diam = Number(v.diamMm) || Number(doc.meta?.defaultViaDiamMm) || 0.8;
        const ap = ensureRoundDiam(diam + MASK_VIA_MARGIN * 2);
        const [gx, gy] = svgToGerber(doc, v.x, v.y, false);
        lines.push(`D${ap}*\n`);
        lines.push(xyLine(gx, gy, 'D03'));
    }

    lines.push('M02*\n');
    return lines.join('');
}

/** Stencil paste: SMD pads only (no plated drill). Top-only placements → B.Paste is empty. */
function buildPasteGerber(doc, mirror) {
    const layerName = mirror ? 'B.Paste' : 'F.Paste';
    const lines = [];
    lines.push(`G04 ${layerName}*`);
    lines.push('G04 Generated by NozePlot PCB Studio*');
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');

    if (mirror) {
        lines.push('G04 No bottom-mounted SMD in doc model — empty paste*\n');
        lines.push('M02*\n');
        return lines.join('');
    }

    const apMap = new Map();
    let nextAp = 10;
    function ensureRoundDiam(diamMm) {
        const key = `C:${fmtMm(diamMm)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}C,${fmtMm(diamMm)}*%\n`);
        return d;
    }
    function ensureRect(w, h) {
        const key = `R:${fmtMm(w)}X${fmtMm(h)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}R,${fmtMm(w)}X${fmtMm(h)}*%\n`);
        return d;
    }

    let any = false;
    for (const pl of doc.placements || []) {
        const fp = getFootprint(pl.footprintId);
        if (!fp) continue;
        for (const pad of fp.pads || []) {
            if (padHasPlatedDrill(pad)) continue;
            any = true;
            const [wx, wy] = padWorld(pl, pad);
            const [gx, gy] = svgToGerber(doc, wx, wy, false);
            const dims = padFlashDims(pad, pl.rot || 0);
            const ap =
                dims.kind === 'R'
                    ? ensureRect(dims.w, dims.h)
                    : ensureRoundDiam(dims.d);
            lines.push(`D${ap}*\n`);
            lines.push(xyLine(gx, gy, 'D03'));
        }
    }

    if (!any) {
        lines.push('G04 No SMD pads — empty paste layer*\n');
    }

    lines.push('M02*\n');
    return lines.join('');
}

function buildEdgeCutsGerber(doc) {
    const W = Number(doc.meta?.boardWmm) || 80;
    const H = Number(doc.meta?.boardHmm) || 50;
    const lines = [];
    lines.push(GERBER_HEADER_EDGE('Edge.Cuts'));
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');
    // Stroke the outline only (no G36/G37). Filled edge polygons render as a solid slab in Gerbv
    // and other viewers — KiCad-style Edge.Cuts is normally a thin closed path.
    lines.push('%ADD10C,0.100*%\n');
    lines.push('D10*\n');
    lines.push(xyLine(0, 0, 'D02'));
    lines.push(xyLine(W, 0, 'D01'));
    lines.push(xyLine(W, H, 'D01'));
    lines.push(xyLine(0, H, 'D01'));
    lines.push(xyLine(0, 0, 'D01'));
    lines.push('M02*\n');
    return lines.join('');
}

function collectPlatedHoles(doc) {
    const defaultDrill = Number(doc.meta?.defaultViaDrillMm) || 0.4;
    const raw = [];

    for (const v of doc.vias || []) {
        const d = Number(v.drillMm) || defaultDrill;
        if (!Number.isFinite(d) || d <= 0) continue;
        const [gx, gy] = svgToGerber(doc, v.x, v.y, false);
        raw.push({ x: gx, y: gy, d });
    }

    for (const pl of doc.placements || []) {
        const fp = getFootprint(pl.footprintId);
        if (!fp) continue;
        for (const pad of fp.pads || []) {
            if (!padHasPlatedDrill(pad)) continue;
            const d = Number(pad.drill);
            const [wx, wy] = padWorld(pl, pad);
            const [gx, gy] = svgToGerber(doc, wx, wy, false);
            raw.push({ x: gx, y: gy, d });
        }
    }

    const seen = new Set();
    const holes = [];
    for (const h of raw) {
        const k = `${Math.round(h.x * 1e4)}_${Math.round(h.y * 1e4)}_${Math.round(h.d * 1e6)}`;
        if (seen.has(k)) continue;
        seen.add(k);
        holes.push(h);
    }
    holes.sort((a, b) => fmtMm(a.d).localeCompare(fmtMm(b.d)) || a.x - b.x || a.y - b.y);
    return holes;
}

function buildExcellonDrill(doc) {
    const lines = [];
    lines.push('M48\n');
    lines.push(';DRILL file from NozePlot PCB Studio (PTH: vias + through-hole pads)\n');
    lines.push('METRIC,LZ\n');
    const holes = collectPlatedHoles(doc);
    const byDrill = new Map();
    let toolIdx = 1;

    for (const h of holes) {
        const key = fmtMm(h.d);
        if (!byDrill.has(key)) {
            byDrill.set(key, toolIdx);
            lines.push(`T${String(toolIdx).padStart(2, '0')}C${key}\n`);
            toolIdx++;
        }
    }

    for (const h of holes) {
        h.t = byDrill.get(fmtMm(h.d));
    }

    lines.push('%\n');
    lines.push('G05\n');
    if (holes.length === 0) {
        lines.push('G04 No plated holes (no vias / THT pads)*\n');
    } else {
        let curT = null;
        for (const h of holes) {
            if (curT !== h.t) {
                curT = h.t;
                lines.push(`T${String(h.t).padStart(2, '0')}\n`);
            }
            lines.push(`X${fmtMm(h.x)}Y${fmtMm(h.y)}\n`);
        }
    }
    lines.push('M30\n');
    return lines.join('');
}

function gerberFileSuffix(layer) {
    return String(layer).replace(/\./g, '_');
}

function buildFabReadme(safe, stack) {
    const layers = stack.join(', ');
    return [
        `Fabrication bundle from NozePlot PCB Studio (${safe})`,
        '',
        'Gerber RS-274X (mm), legacy headers (no X2 %TF).',
        '',
        'Typical stack (outer → inner — confirm with your fab):',
        `  Copper: ${layers}`,
        '  F_SilkS — top silk from library; B_SilkS empty (top-only footprints here)',
        '  F_Mask — openings for all pads + vias; B_Mask — vias + THT only (same board XY as F — not X-mirrored)',
        '  F_Paste — top SMD stencil; B_Paste empty until bottom-side parts exist',
        '  Edge_Cuts — board outline as a stroked rectangle (not filled — matches Gerbv / fab expectation)',
        '  PTH.drl — Excellon plated holes (vias + THT pad drills)',
        '',
        'Review: ring sizes, paste reduction, and inner-layer pad annuli with your fab.',
        '',
    ].join('\n');
}

/**
 * @param {object} doc
 * @param {string} baseName
 * @returns {Promise<Blob>}
 */
export async function buildPcbFabricationZip(doc, baseName = 'pcb_export') {
    const safe = String(baseName || 'pcb')
        .replace(/[^\w-]+/g, '_')
        .slice(0, 64);
    const zip = new JSZip();
    const stack = activeCopperLayerIds(doc);

    zip.file(`${safe}-README_FAB.txt`, buildFabReadme(safe, stack));

    zip.file(`${safe}-Edge_Cuts.gbr`, buildEdgeCutsGerber(doc));

    for (const layer of stack) {
        zip.file(`${safe}-${gerberFileSuffix(layer)}.gbr`, buildCopperGerber(doc, layer));
    }

    zip.file(`${safe}-F_SilkS.gbr`, buildSilkScreenGerber(doc, false));
    zip.file(`${safe}-B_SilkS.gbr`, buildSilkScreenGerber(doc, true));

    zip.file(`${safe}-F_Mask.gbr`, buildSoldermaskGerber(doc, false));
    zip.file(`${safe}-B_Mask.gbr`, buildSoldermaskGerber(doc, true));

    zip.file(`${safe}-F_Paste.gbr`, buildPasteGerber(doc, false));
    zip.file(`${safe}-B_Paste.gbr`, buildPasteGerber(doc, true));

    zip.file(`${safe}-PTH.drl`, buildExcellonDrill(doc));

    return zip.generateAsync({ type: 'blob' });
}

export function triggerBlobDownload(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}
