/**
 * Build RS-274X Gerbers (all active copper + Edge.Cuts) + Excellon drill ZIP from a PcbDoc.
 * PCB Studio uses SVG-style coords (origin top-left, Y down, mm). Gerber uses Y up.
 */

import JSZip from 'jszip';
import { getFootprint } from './footprintLib.js';
import { activeCopperLayerIds } from './pcbDoc.js';

const GERBER_HEADER_EDGE = (name) =>
    [
        'G04 ' + (name || 'Edge.Cuts') + '*',
        'G04 Generated by NozePlot PCB Studio*',
        '%TF.FileFunction,Profile,NP*%',
    ].join('\n') + '\n';

function buildCopperGerberHeader(layer, stack) {
    const idx = stack.indexOf(layer) + 1;
    const n = stack.length;
    let fileFunc = `%TF.FileFunction,Copper,L${idx},Inr*%`;
    if (layer === 'F.Cu') fileFunc = '%TF.FileFunction,Copper,L1,Top*%';
    if (layer === 'B.Cu') fileFunc = `%TF.FileFunction,Copper,L${n},Bot*%`;
    return ['G04 ' + layer + '*', 'G04 Generated by NozePlot PCB Studio*', fileFunc, '%TF.Part,Single*%'].join('\n') + '\n';
}

function fmtMm(mm) {
    const v = Math.round(Number(mm) * 1e6) / 1e6;
    let s = v.toFixed(6);
    if (s.includes('.')) {
        s = s.replace(/\.?0+$/, '');
    }
    return s;
}

function xyLine(x, y, op) {
    return `X${fmtMm(x)}Y${fmtMm(y)}${op}*\n`;
}

function mirrorX(boardW, x) {
    return boardW - x;
}

function rotLocal(x, y, deg) {
    const r = ((Number(deg) || 0) * Math.PI) / 180;
    const c = Math.cos(r);
    const s = Math.sin(r);
    return [x * c - y * s, x * s + y * c];
}

function padWorld(pl, pad) {
    const [lx, ly] = rotLocal(pad.x, pad.y, pl.rot || 0);
    return [lx + pl.x, ly + pl.y];
}

function svgToGerber(doc, svgX, svgY, mirror) {
    const W = Number(doc.meta?.boardWmm) || 80;
    const H = Number(doc.meta?.boardHmm) || 50;
    const gx = mirror ? mirrorX(W, svgX) : svgX;
    const gy = H - svgY;
    return [gx, gy];
}

function padFlashDims(pad, rotDeg) {
    const r = ((Number(rotDeg) || 0) % 360 + 360) % 360;
    const snap = Math.round(r / 90) % 4;
    if (Math.abs(r - snap * 90) < 0.01) {
        if (snap % 2 === 1) return { kind: 'R', w: pad.h, h: pad.w };
        return { kind: 'R', w: pad.w, h: pad.h };
    }
    return { kind: 'C', d: Math.max(pad.w, pad.h) * 0.95 };
}

function buildCopperGerber(doc, layer, stack) {
    const mirror = layer === 'B.Cu';
    const lines = [];
    lines.push(buildCopperGerberHeader(layer, stack));
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');

    const apMap = new Map();
    let nextAp = 10;

    function ensureRoundDiam(diamMm) {
        const key = `C:${fmtMm(diamMm)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}C,${fmtMm(diamMm)}*%\n`);
        return d;
    }

    function ensureRect(w, h) {
        const key = `R:${fmtMm(w)}X${fmtMm(h)}`;
        if (apMap.has(key)) return apMap.get(key);
        const d = nextAp++;
        apMap.set(key, d);
        lines.push(`%ADD${d}R,${fmtMm(w)}X${fmtMm(h)}*%\n`);
        return d;
    }

    if (layer === 'F.Cu') {
        for (const pl of doc.placements || []) {
            const fp = getFootprint(pl.footprintId);
            if (!fp) continue;
            for (const pad of fp.pads || []) {
                const [wx, wy] = padWorld(pl, pad);
                const [gx, gy] = svgToGerber(doc, wx, wy, mirror);
                const dims = padFlashDims(pad, pl.rot || 0);
                const ap =
                    dims.kind === 'R'
                        ? ensureRect(dims.w, dims.h)
                        : ensureRoundDiam(dims.d);
                lines.push(`D${ap}*\n`);
                lines.push(xyLine(gx, gy, 'D03'));
            }
        }
    }

    for (const v of doc.vias || []) {
        const diam = Number(v.diamMm) || Number(doc.meta?.defaultViaDiamMm) || 0.8;
        const ap = ensureRoundDiam(diam);
        const [gx, gy] = svgToGerber(doc, v.x, v.y, mirror);
        lines.push(`D${ap}*\n`);
        lines.push(xyLine(gx, gy, 'D03'));
    }

    const tracks = (doc.tracks || []).filter((t) => t.layer === layer);
    for (const tr of tracks) {
        const pts = tr.points || [];
        if (pts.length < 2) continue;
        const w = Number(tr.widthMm) || Number(doc.meta?.defaultTrackMm) || 0.35;
        const ap = ensureRoundDiam(w);
        lines.push(`D${ap}*\n`);
        const p0 = pts[0];
        const [g0x, g0y] = svgToGerber(doc, p0[0], p0[1], mirror);
        lines.push(xyLine(g0x, g0y, 'D02'));
        for (let i = 1; i < pts.length; i++) {
            const p = pts[i];
            const [gx, gy] = svgToGerber(doc, p[0], p[1], mirror);
            lines.push(xyLine(gx, gy, 'D01'));
        }
    }

    const polys = (doc.polygons || []).filter((p) => p.layer === layer);
    for (const poly of polys) {
        const pts = poly.points || [];
        if (pts.length < 3) continue;
        lines.push('G36*\n');
        const [gx0, gy0] = svgToGerber(doc, pts[0][0], pts[0][1], mirror);
        lines.push(xyLine(gx0, gy0, 'D02'));
        for (let i = 1; i < pts.length; i++) {
            const [gx, gy] = svgToGerber(doc, pts[i][0], pts[i][1], mirror);
            lines.push(xyLine(gx, gy, 'D01'));
        }
        lines.push(xyLine(gx0, gy0, 'D01'));
        lines.push('G37*\n');
    }

    lines.push('M02*\n');
    return lines.join('');
}

function buildEdgeCutsGerber(doc) {
    const W = Number(doc.meta?.boardWmm) || 80;
    const H = Number(doc.meta?.boardHmm) || 50;
    const lines = [];
    lines.push(GERBER_HEADER_EDGE('Edge.Cuts'));
    lines.push('%FSLAX46Y46*%\n');
    lines.push('%MOMM*%\n');
    lines.push('%LPD*%\n');
    lines.push('G01*\n');
    lines.push('%ADD10C,0.100*%\n');
    lines.push('D10*\n');
    lines.push('G36*\n');
    lines.push(xyLine(0, 0, 'D02'));
    lines.push(xyLine(W, 0, 'D01'));
    lines.push(xyLine(W, H, 'D01'));
    lines.push(xyLine(0, H, 'D01'));
    lines.push(xyLine(0, 0, 'D01'));
    lines.push('G37*\n');
    lines.push('M02*\n');
    return lines.join('');
}

function buildExcellonDrill(doc) {
    const lines = [];
    lines.push('M48\n');
    lines.push(';DRILL file from NozePlot PCB Studio\n');
    lines.push('METRIC,LZ\n');
    const byDrill = new Map();
    let toolIdx = 1;
    const holes = [];

    const defaultDrill = Number(doc.meta?.defaultViaDrillMm) || 0.4;

    for (const v of doc.vias || []) {
        const d = Number(v.drillMm) || defaultDrill;
        const key = fmtMm(d);
        if (!byDrill.has(key)) {
            byDrill.set(key, toolIdx);
            lines.push(`T${String(toolIdx).padStart(2, '0')}C${key}\n`);
            toolIdx++;
        }
        const [gx, gy] = svgToGerber(doc, v.x, v.y, false);
        holes.push({ t: byDrill.get(key), x: gx, y: gy });
    }

    lines.push('%\n');
    lines.push('G05\n');
    if (holes.length === 0) {
        lines.push('G04 No plated holes (no vias placed)*\n');
    } else {
        let curT = null;
        for (const h of holes) {
            if (curT !== h.t) {
                curT = h.t;
                lines.push(`T${String(h.t).padStart(2, '0')}\n`);
            }
            lines.push(`X${fmtMm(h.x)}Y${fmtMm(h.y)}\n`);
        }
    }
    lines.push('M30\n');
    return lines.join('');
}

function gerberFileSuffix(layer) {
    return String(layer).replace(/\./g, '_');
}

/**
 * @param {object} doc
 * @param {string} baseName
 * @returns {Promise<Blob>}
 */
export async function buildPcbFabricationZip(doc, baseName = 'pcb_export') {
    const safe = String(baseName || 'pcb')
        .replace(/[^\w-]+/g, '_')
        .slice(0, 64);
    const zip = new JSZip();
    zip.file(`${safe}-Edge_Cuts.gbr`, buildEdgeCutsGerber(doc));
    const stack = activeCopperLayerIds(doc);
    for (const layer of stack) {
        zip.file(`${safe}-${gerberFileSuffix(layer)}.gbr`, buildCopperGerber(doc, layer, stack));
    }
    zip.file(`${safe}-PTH.drl`, buildExcellonDrill(doc));
    return zip.generateAsync({ type: 'blob' });
}

export function triggerBlobDownload(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}
